import { CheckCircleOutlined, ClockCircleOutlined, ExclamationCircleOutlined, InboxOutlined, MinusCircleOutlined, PhoneOutlined } from "@ant-design/icons";

export const statusColors = {
    "Pending": "blue",
    "Booked Appointment": "cyan",
    "Received": "green",
    "Approved": "gold",
    "In Progress": "gold",
    "Sent to Valuation": "purple",
    "Completed": "green",
    "Start Valuated": "gold",
    "Valuated": "purple",
    "Commitment": "orange",
    "Sealing": "orange",
    "Result Sent to Customer": "purple",
    "Received for Valuation": "cyan",
    "Sent to Consulting": "cyan",
    "Unprocessed": "red",
    "Ready for valuation": "blue"
};

export const serviceColors = {
    "Advanced Valuation": "black",
    "Basic Valuation": ""
};

export const statusIcons = {
    "Pending": <ClockCircleOutlined />,
    "Booked Appointment": <PhoneOutlined />,
    "Received": <InboxOutlined />,
    "Approved": <ExclamationCircleOutlined />,
    "In Progress": <ClockCircleOutlined />,
    "Sent to Valuation": <ClockCircleOutlined />,
    "Completed": <CheckCircleOutlined />,
    "Start Valuated": <ClockCircleOutlined />,
    "Valuated": <ExclamationCircleOutlined />,
    "Commitment": <ClockCircleOutlined />,
    "Sealing": <ClockCircleOutlined />,
    "Result Sent to Customer": <ExclamationCircleOutlined />,
    "Received for Valuation": <InboxOutlined />,
    "Sent to Consulting": <InboxOutlined />,
    "Unprocessed": <MinusCircleOutlined />,
    "Ready for valuation": <CheckCircleOutlined />
};
export const shapeOptions = ["Round", "Princess", "Oval", "Marquise", "Pear", "Heart", "Cushion", "Radiant", "Emerald", "Asscher"];
export const colorOptions = ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N"];
export const clarityOptions = ["IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2", "SI", "I1", "I2", "I3"];
export const cutOptions = ["Affinity", "Excellent", "VeryGood", "Good", "Fair"];
export const fluorescenceOptions = ["None", "Faint", "Medium", "Strong", "VeryStrong"];
export const polishOptions = ["Excellent", "VeryGood", "Good", "Fair", "Poor"];
export const symmetryOptions = ["Excellent", "VeryGood", "Good", "Fair", "Poor"];
export const proportionsOptions = ["Ideal", "Excellent", "VeryGood", "Good", "Fair"];
export const measurementsOptions = ["Small", "Medium", "Large"];

export const countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
    'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
    'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Costa Rica',
    'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
    'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
    'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel',
    'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
    'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
    'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia',
    'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
    'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
    'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
    'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe',
    'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
    'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
    'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
    'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
    'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'
];

export const chartByshapes = [
    { shape: 'Round', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.3_carat.svg' },
    { shape: 'Princess', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.3_carat.svg' },
    { shape: 'Oval', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.3_carat.svg' },
    { shape: 'Marquise', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.3_carat.svg' },
    { shape: 'Pear', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.3_carat.svg' },
    { shape: 'Heart', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.3_carat.svg' },
    { shape: 'Cushion', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.3_carat.svg' },
    { shape: 'Radiant', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.3_carat.svg' },
    { shape: 'Emerald', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.3_carat.svg' },
    { shape: 'Asscher', carat: '0.3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.3_carat.svg' },
    { shape: 'Round', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.4_carat.svg' },
    { shape: 'Princess', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.4_carat.svg' },
    { shape: 'Oval', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.4_carat.svg' },
    { shape: 'Marquise', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.4_carat.svg' },
    { shape: 'Pear', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.4_carat.svg' },
    { shape: 'Heart', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.4_carat.svg' },
    { shape: 'Cushion', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.4_carat.svg' },
    { shape: 'Radiant', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.4_carat.svg' },
    { shape: 'Emerald', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.4_carat.svg' },
    { shape: 'Asscher', carat: '0.4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.4_carat.svg' },
    { shape: 'Round', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.5_carat.svg' },
    { shape: 'Princess', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.5_carat.svg' },
    { shape: 'Oval', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.5_carat.svg' },
    { shape: 'Marquise', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.5_carat.svg' },
    { shape: 'Pear', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.5_carat.svg' },
    { shape: 'Heart', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.5_carat.svg' },
    { shape: 'Cushion', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.5_carat.svg' },
    { shape: 'Radiant', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.5_carat.svg' },
    { shape: 'Emerald', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.5_carat.svg' },
    { shape: 'Asscher', carat: '0.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.5_carat.svg' },
    { shape: 'Round', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.6_carat.svg' },
    { shape: 'Princess', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.6_carat.svg' },
    { shape: 'Oval', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.6_carat.svg' },
    { shape: 'Marquise', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.6_carat.svg' },
    { shape: 'Pear', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.6_carat.svg' },
    { shape: 'Heart', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.6_carat.svg' },
    { shape: 'Cushion', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.6_carat.svg' },
    { shape: 'Radiant', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.6_carat.svg' },
    { shape: 'Emerald', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.6_carat.svg' },
    { shape: 'Asscher', carat: '0.6', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.6_carat.svg' },
    { shape: 'Round', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.7_carat.svg' },
    { shape: 'Princess', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.7_carat.svg' },
    { shape: 'Oval', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.7_carat.svg' },
    { shape: 'Marquise', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.7_carat.svg' },
    { shape: 'Pear', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.7_carat.svg' },
    { shape: 'Heart', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.7_carat.svg' },
    { shape: 'Cushion', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.7_carat.svg' },
    { shape: 'Radiant', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.7_carat.svg' },
    { shape: 'Emerald', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.7_carat.svg' },
    { shape: 'Asscher', carat: '0.7', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.7_carat.svg' },
    { shape: 'Round', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.8_carat.svg' },
    { shape: 'Princess', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.8_carat.svg' },
    { shape: 'Oval', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.8_carat.svg' },
    { shape: 'Marquise', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.8_carat.svg' },
    { shape: 'Pear', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.8_carat.svg' },
    { shape: 'Heart', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.8_carat.svg' },
    { shape: 'Cushion', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.8_carat.svg' },
    { shape: 'Radiant', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.8_carat.svg' },
    { shape: 'Emerald', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.8_carat.svg' },
    { shape: 'Asscher', carat: '0.8', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.8_carat.svg' },
    { shape: 'Round', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_0.9_carat.svg' },
    { shape: 'Princess', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_0.9_carat.svg' },
    { shape: 'Oval', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_0.9_carat.svg' },
    { shape: 'Marquise', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_0.9_carat.svg' },
    { shape: 'Pear', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_0.9_carat.svg' },
    { shape: 'Heart', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_0.9_carat.svg' },
    { shape: 'Cushion', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_0.9_carat.svg' },
    { shape: 'Radiant', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_0.9_carat.svg' },
    { shape: 'Emerald', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_0.9_carat.svg' },
    { shape: 'Asscher', carat: '0.9', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_0.9_carat.svg' },
    { shape: 'Round', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_1_carat.svg' },
    { shape: 'Princess', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_1_carat.svg' },
    { shape: 'Oval', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_1_carat.svg' },
    { shape: 'Marquise', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_1_carat.svg' },
    { shape: 'Pear', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_1_carat.svg' },
    { shape: 'Heart', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_1_carat.svg' },
    { shape: 'Cushion', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_1_carat.svg' },
    { shape: 'Radiant', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_1_carat.svg' },
    { shape: 'Emerald', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_1_carat.svg' },
    { shape: 'Asscher', carat: '1', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_1_carat.svg' },
    { shape: 'Round', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_1.5_carat.svg' },
    { shape: 'Princess', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_1.5_carat.svg' },
    { shape: 'Oval', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_1.5_carat.svg' },
    { shape: 'Marquise', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_1.5_carat.svg' },
    { shape: 'Pear', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_1.5_carat.svg' },
    { shape: 'Heart', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_1.5_carat.svg' },
    { shape: 'Cushion', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_1.5_carat.svg' },
    { shape: 'Radiant', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_1.5_carat.svg' },
    { shape: 'Emerald', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_1.5_carat.svg' },
    { shape: 'Asscher', carat: '1.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_1.5_carat.svg' },
    { shape: 'Round', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_2_carat.svg' },
    { shape: 'Princess', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_2_carat.svg' },
    { shape: 'Oval', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_2_carat.svg' },
    { shape: 'Marquise', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_2_carat.svg' },
    { shape: 'Pear', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_2_carat.svg' },
    { shape: 'Heart', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_2_carat.svg' },
    { shape: 'Cushion', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_2_carat.svg' },
    { shape: 'Radiant', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_2_carat.svg' },
    { shape: 'Emerald', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_2_carat.svg' },
    { shape: 'Asscher', carat: '2', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_2_carat.svg' },
    { shape: 'Round', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_2.5_carat.svg' },
    { shape: 'Princess', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_2.5_carat.svg' },
    { shape: 'Oval', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_2.5_carat.svg' },
    { shape: 'Marquise', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_2.5_carat.svg' },
    { shape: 'Pear', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_2.5_carat.svg' },
    { shape: 'Heart', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_2.5_carat.svg' },
    { shape: 'Cushion', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_2.5_carat.svg' },
    { shape: 'Radiant', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_2.5_carat.svg' },
    { shape: 'Emerald', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_2.5_carat.svg' },
    { shape: 'Asscher', carat: '2.5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_2.5_carat.svg' },
    { shape: 'Round', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_3_carat.svg' },
    { shape: 'Princess', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_3_carat.svg' },
    { shape: 'Oval', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_3_carat.svg' },
    { shape: 'Marquise', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_3_carat.svg' },
    { shape: 'Pear', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_3_carat.svg' },
    { shape: 'Heart', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_3_carat.svg' },
    { shape: 'Cushion', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_3_carat.svg' },
    { shape: 'Radiant', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_3_carat.svg' },
    { shape: 'Emerald', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_3_carat.svg' },
    { shape: 'Asscher', carat: '3', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_3_carat.svg' },
    { shape: 'Round', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_4_carat.svg' },
    { shape: 'Princess', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_4_carat.svg' },
    { shape: 'Oval', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_4_carat.svg' },
    { shape: 'Marquise', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_4_carat.svg' },
    { shape: 'Pear', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_4_carat.svg' },
    { shape: 'Heart', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_4_carat.svg' },
    { shape: 'Cushion', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_4_carat.svg' },
    { shape: 'Radiant', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_4_carat.svg' },
    { shape: 'Emerald', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_4_carat.svg' },
    { shape: 'Asscher', carat: '4', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_4_carat.svg' },
    { shape: 'Round', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Round_5_carat.svg' },
    { shape: 'Princess', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Princess_5_carat.svg' },
    { shape: 'Oval', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Oval_5_carat.svg' },
    { shape: 'Marquise', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Marquise_5_carat.svg' },
    { shape: 'Pear', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Pear_5_carat.svg' },
    { shape: 'Heart', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Heart_5_carat.svg' },
    { shape: 'Cushion', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Cushion_5_carat.svg' },
    { shape: 'Radiant', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Radiant_5_carat.svg' },
    { shape: 'Emerald', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Emerald_5_carat.svg' },
    { shape: 'Asscher', carat: '5', url: 'https://stonealgo-cert.b-cdn.net/img-q4m8c3hsmq/1m_Asscher_5_carat.svg' },
];

export const chartData = [
    { carat: '0.3', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.3_carat.svg' },
    { carat: '0.4', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.4_carat.svg' },
    { carat: '0.5', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.5_carat.svg' },
    { carat: '0.6', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.6_carat.svg' },
    { carat: '0.7', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.7_carat.svg' },
    { carat: '0.8', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.8_carat.svg' },
    { carat: '0.9', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_0.9_carat.svg' },
    { carat: '1', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_1_carat.svg' },
    { carat: '1.5', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_1.5_carat.svg' },
    { carat: '2', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_2_carat.svg' },
    { carat: '2.5', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_2.5_carat.svg' },
    { carat: '3', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_3_carat.svg' },
    { carat: '4', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_4_carat.svg' },
    { carat: '5', url: 'https://stonealgo.blob.core.windows.net/img-q4m8c3hsmq/1m_All_5_carat.svg' },
];

export const emojiMap = {
    ':)': '😊',
    ':(': '😞',
    '<3': '❤️',
    ':D': '😄',
    ';)': '😉',
    ':P': '😛',
    ':O': '😮',
    ':*': '😘',
    ':|': '😐',
    ':/': '😕',
    ':B': '😎',
    '>:(': '😡',
    ':X': '🤐',
    ':>': '😏',
    'O:)': '😇',
    ':poop:': '💩',
    ':fire:': '🔥',
    ':thumbsup:': '👍',
    ':thumbsdown:': '👎',
};